version: "3.8"
services:
  frontend:
    build: .
    ports:
      - 8070:80
    tty: true
    restart: always
    labels:
      - "traefik.http.routers.frontend.rule=Host(`flask.tilburgsciencehub.com`)"
